// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EndpointService 端点管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateEndpoint 创建新端点
 */
export function CreateEndpoint(moduleID: string, folderID: string | null, name: string, method: string, path: string): $CancellablePromise<models$0.Endpoint | null> {
    return $Call.ByID(1012481058, moduleID, folderID, name, method, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteEndpoint 删除端点及其关联数据
 */
export function DeleteEndpoint(id: string): $CancellablePromise<void> {
    return $Call.ByID(415554709, id);
}

/**
 * EndpointToJSON 将端点导出为 JSON
 */
export function EndpointToJSON(endpoint: $models.EndpointDetail | null): $CancellablePromise<string> {
    return $Call.ByID(2048768381, endpoint);
}

/**
 * GetEndpoint 获取端点完整详情
 */
export function GetEndpoint(id: string): $CancellablePromise<$models.EndpointDetail | null> {
    return $Call.ByID(3617303864, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetEndpointsByFolder 获取文件夹下的端点列表
 */
export function GetEndpointsByFolder(folderID: string): $CancellablePromise<models$0.Endpoint[]> {
    return $Call.ByID(1442728116, folderID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetEndpointsByModule 获取模块下直属的端点列表
 */
export function GetEndpointsByModule(moduleID: string): $CancellablePromise<models$0.Endpoint[]> {
    return $Call.ByID(2141584120, moduleID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SaveEndpointData 保存端点所有数据
 */
export function SaveEndpointData(data: $models.EndpointSaveData): $CancellablePromise<void> {
    return $Call.ByID(3987759759, data);
}

/**
 * SaveResponse 保存端点响应（upsert）
 */
export function SaveResponse(endpointID: string, resp: models$0.Response | null): $CancellablePromise<void> {
    return $Call.ByID(2237366293, endpointID, resp);
}

/**
 * SearchEndpoints 在模块中搜索端点
 */
export function SearchEndpoints(moduleID: string, query: string): $CancellablePromise<models$0.Endpoint[]> {
    return $Call.ByID(4164722091, moduleID, query).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Endpoint.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.EndpointDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
