// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentService 环境管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateEnvironment 创建新环境
 */
export function CreateEnvironment(projectID: string, name: string): $CancellablePromise<models$0.Environment | null> {
    return $Call.ByID(3291281510, projectID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteEnvironment 删除环境及其变量
 */
export function DeleteEnvironment(id: string): $CancellablePromise<void> {
    return $Call.ByID(3067525859, id);
}

/**
 * GetEnvironment 获取环境详情（包含变量）
 */
export function GetEnvironment(id: string): $CancellablePromise<models$0.Environment | null> {
    return $Call.ByID(1983907996, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEnvironmentVariables 获取环境的所有变量
 */
export function GetEnvironmentVariables(environmentID: string): $CancellablePromise<models$0.EnvironmentVariable[]> {
    return $Call.ByID(2480742821, environmentID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListEnvironments 获取项目下所有环境
 */
export function ListEnvironments(projectID: string): $CancellablePromise<models$0.Environment[]> {
    return $Call.ByID(729861219, projectID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ResolveVariables 替换字符串中的环境变量占位符
 * 占位符格式：{{variableName}}
 */
export function ResolveVariables(environmentID: string, input: string): $CancellablePromise<string> {
    return $Call.ByID(3165963104, environmentID, input);
}

/**
 * SaveEnvironmentVariables 保存环境的所有变量
 */
export function SaveEnvironmentVariables(environmentID: string, variables: models$0.EnvironmentVariable[]): $CancellablePromise<void> {
    return $Call.ByID(3542389586, environmentID, variables);
}

/**
 * UpdateEnvironment 更新环境名称
 */
export function UpdateEnvironment(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(579953697, id, name);
}

// Private type creation functions
const $$createType0 = models$0.Environment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.EnvironmentVariable.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
