// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderService 文件夹管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateFolder 创建新文件夹
 */
export function CreateFolder(moduleID: string, parentID: string | null, name: string): $CancellablePromise<models$0.Folder | null> {
    return $Call.ByID(3674059286, moduleID, parentID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteFolder 删除文件夹及其所有子内容
 */
export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(2065195493, id);
}

/**
 * MoveFolder 移动文件夹到新的父文件夹
 */
export function MoveFolder(id: string, parentID: string | null): $CancellablePromise<void> {
    return $Call.ByID(2166528987, id, parentID);
}

/**
 * UpdateFolder 更新文件夹信息
 */
export function UpdateFolder(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2450328911, id, name);
}

// Private type creation functions
const $$createType0 = models$0.Folder.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
