// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HTTPService HTTP 请求服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SendRequest 发送 HTTP 请求
 */
export function SendRequest(data: $models.SendRequestData): $CancellablePromise<$models.HTTPResponseData | null> {
    return $Call.ByID(2080370785, data).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HTTPResponseData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
