// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportExportService 导入导出服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * ExportProject 导出项目为 JSON
 */
export function ExportProject(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(2217023388, projectID);
}

/**
 * ImportProject 从 JSON 导入项目
 */
export function ImportProject(jsonStr: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(2027421429, jsonStr).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
