// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * EndpointDetail 端点完整详情（包含所有关联数据）
 */
export class EndpointDetail {
    "id": string;
    "moduleId": string;
    "folderId": string | null;
    "name": string;
    "method": string;
    "path": string;
    "bodyType": string;
    "bodyContent": string;
    "contentType": string;
    "timeout": number;
    "followRedirects": boolean;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "params": models$0.EndpointParam[];
    "bodyFields": models$0.EndpointBodyField[];
    "headers": models$0.EndpointHeader[];
    "auth": models$0.EndpointAuth | null;
    "response": models$0.Response | null;

    /** Creates a new EndpointDetail instance. */
    constructor($$source: Partial<EndpointDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bodyType" in $$source)) {
            this["bodyType"] = "";
        }
        if (!("bodyContent" in $$source)) {
            this["bodyContent"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("params" in $$source)) {
            this["params"] = [];
        }
        if (!("bodyFields" in $$source)) {
            this["bodyFields"] = [];
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("auth" in $$source)) {
            this["auth"] = null;
        }
        if (!("response" in $$source)) {
            this["response"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointDetail {
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType5;
        const $$createField17_0 = $$createType7;
        const $$createField18_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField14_0($$parsedSource["params"]);
        }
        if ("bodyFields" in $$parsedSource) {
            $$parsedSource["bodyFields"] = $$createField15_0($$parsedSource["bodyFields"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField16_0($$parsedSource["headers"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField17_0($$parsedSource["auth"]);
        }
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField18_0($$parsedSource["response"]);
        }
        return new EndpointDetail($$parsedSource as Partial<EndpointDetail>);
    }
}

/**
 * EndpointSaveData 端点保存数据
 */
export class EndpointSaveData {
    "id": string;
    "name": string;
    "method": string;
    "path": string;
    "bodyType": string;
    "bodyContent": string;
    "contentType": string;
    "timeout": number;
    "followRedirects": boolean;
    "params": models$0.EndpointParam[];
    "bodyFields": models$0.EndpointBodyField[];
    "headers": models$0.EndpointHeader[];
    "auth": models$0.EndpointAuth | null;

    /** Creates a new EndpointSaveData instance. */
    constructor($$source: Partial<EndpointSaveData> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bodyType" in $$source)) {
            this["bodyType"] = "";
        }
        if (!("bodyContent" in $$source)) {
            this["bodyContent"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }
        if (!("params" in $$source)) {
            this["params"] = [];
        }
        if (!("bodyFields" in $$source)) {
            this["bodyFields"] = [];
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("auth" in $$source)) {
            this["auth"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointSaveData instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointSaveData {
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType5;
        const $$createField12_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        if ("bodyFields" in $$parsedSource) {
            $$parsedSource["bodyFields"] = $$createField10_0($$parsedSource["bodyFields"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField11_0($$parsedSource["headers"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField12_0($$parsedSource["auth"]);
        }
        return new EndpointSaveData($$parsedSource as Partial<EndpointSaveData>);
    }
}

/**
 * FolderTree 文件夹树形结构
 */
export class FolderTree {
    "id": string;
    "moduleId": string;
    "parentId": string | null;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "children": FolderTree[];
    "endpoints": models$0.Endpoint[];

    /** Creates a new FolderTree instance. */
    constructor($$source: Partial<FolderTree> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }
        if (!("endpoints" in $$source)) {
            this["endpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderTree instance from a string or object.
     */
    static createFrom($$source: any = {}): FolderTree {
        const $$createField7_0 = $$createType11;
        const $$createField8_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField8_0($$parsedSource["endpoints"]);
        }
        return new FolderTree($$parsedSource as Partial<FolderTree>);
    }
}

/**
 * HTTPResponseData HTTP 响应数据
 */
export class HTTPResponseData {
    "statusCode": number;
    "headers": { [_ in string]?: string[] };
    "body": string;
    "contentType": string;
    "cookies": models$0.CookieInfo[];
    "timing": models$0.TimingInfo;
    "size": number;
    "actualRequest": models$0.ActualRequestInfo;

    /** Creates a new HTTPResponseData instance. */
    constructor($$source: Partial<HTTPResponseData> = {}) {
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("cookies" in $$source)) {
            this["cookies"] = [];
        }
        if (!("timing" in $$source)) {
            this["timing"] = (new models$0.TimingInfo());
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("actualRequest" in $$source)) {
            this["actualRequest"] = (new models$0.ActualRequestInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPResponseData instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPResponseData {
        const $$createField1_0 = $$createType15;
        const $$createField4_0 = $$createType17;
        const $$createField5_0 = $$createType18;
        const $$createField7_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        if ("cookies" in $$parsedSource) {
            $$parsedSource["cookies"] = $$createField4_0($$parsedSource["cookies"]);
        }
        if ("timing" in $$parsedSource) {
            $$parsedSource["timing"] = $$createField5_0($$parsedSource["timing"]);
        }
        if ("actualRequest" in $$parsedSource) {
            $$parsedSource["actualRequest"] = $$createField7_0($$parsedSource["actualRequest"]);
        }
        return new HTTPResponseData($$parsedSource as Partial<HTTPResponseData>);
    }
}

/**
 * HistoryDetail 请求历史详情
 */
export class HistoryDetail {
    "id": string;
    "moduleId": string;
    "endpointId": string | null;
    "method": string;
    "url": string;
    "statusCode": number;

    /**
     * JSON 格式 TimingInfo
     */
    "timing": string;
    "size": number;
    "createdAt": time$0.Time;
    "timingInfo"?: models$0.TimingInfo | null;

    /** Creates a new HistoryDetail instance. */
    constructor($$source: Partial<HistoryDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = null;
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("timing" in $$source)) {
            this["timing"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryDetail {
        const $$createField9_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timingInfo" in $$parsedSource) {
            $$parsedSource["timingInfo"] = $$createField9_0($$parsedSource["timingInfo"]);
        }
        return new HistoryDetail($$parsedSource as Partial<HistoryDetail>);
    }
}

/**
 * ModuleTree 模块树形结构
 */
export class ModuleTree {
    "id": string;
    "projectId": string;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 关联
     */
    "baseUrls"?: models$0.ModuleBaseURL[];
    "folders": FolderTree[];
    "endpoints": models$0.Endpoint[];

    /** Creates a new ModuleTree instance. */
    constructor($$source: Partial<ModuleTree> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("folders" in $$source)) {
            this["folders"] = [];
        }
        if (!("endpoints" in $$source)) {
            this["endpoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuleTree instance from a string or object.
     */
    static createFrom($$source: any = {}): ModuleTree {
        const $$createField6_0 = $$createType22;
        const $$createField7_0 = $$createType11;
        const $$createField8_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseUrls" in $$parsedSource) {
            $$parsedSource["baseUrls"] = $$createField6_0($$parsedSource["baseUrls"]);
        }
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField7_0($$parsedSource["folders"]);
        }
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField8_0($$parsedSource["endpoints"]);
        }
        return new ModuleTree($$parsedSource as Partial<ModuleTree>);
    }
}

/**
 * SendRequestData 发送请求的参数
 */
export class SendRequestData {
    "endpointId": string;
    "moduleId": string;
    "environmentId": string;
    "method": string;
    "baseUrl": string;
    "path": string;
    "headers": models$0.EndpointHeader[];
    "params": models$0.EndpointParam[];
    "bodyType": string;
    "bodyContent": string;
    "contentType": string;
    "bodyFields": models$0.EndpointBodyField[];
    "auth": models$0.EndpointAuth | null;
    "timeout": number;
    "followRedirects": boolean;

    /** Creates a new SendRequestData instance. */
    constructor($$source: Partial<SendRequestData> = {}) {
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("environmentId" in $$source)) {
            this["environmentId"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("params" in $$source)) {
            this["params"] = [];
        }
        if (!("bodyType" in $$source)) {
            this["bodyType"] = "";
        }
        if (!("bodyContent" in $$source)) {
            this["bodyContent"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("bodyFields" in $$source)) {
            this["bodyFields"] = [];
        }
        if (!("auth" in $$source)) {
            this["auth"] = null;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendRequestData instance from a string or object.
     */
    static createFrom($$source: any = {}): SendRequestData {
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType1;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField7_0($$parsedSource["params"]);
        }
        if ("bodyFields" in $$parsedSource) {
            $$parsedSource["bodyFields"] = $$createField11_0($$parsedSource["bodyFields"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField12_0($$parsedSource["auth"]);
        }
        return new SendRequestData($$parsedSource as Partial<SendRequestData>);
    }
}

// Private type creation functions
const $$createType0 = models$0.EndpointParam.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.EndpointBodyField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = models$0.EndpointHeader.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = models$0.EndpointAuth.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = models$0.Response.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = FolderTree.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.Endpoint.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = models$0.CookieInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = models$0.TimingInfo.createFrom;
const $$createType19 = models$0.ActualRequestInfo.createFrom;
const $$createType20 = $Create.Nullable($$createType18);
const $$createType21 = models$0.ModuleBaseURL.createFrom;
const $$createType22 = $Create.Array($$createType21);
