// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModuleService 模块管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateModule 在项目中创建新模块
 */
export function CreateModule(projectID: string, name: string): $CancellablePromise<models$0.Module | null> {
    return $Call.ByID(2711850218, projectID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteModule 删除模块及其所有关联数据
 */
export function DeleteModule(id: string): $CancellablePromise<void> {
    return $Call.ByID(84883037, id);
}

/**
 * GetModule 根据 ID 获取模块
 */
export function GetModule(id: string): $CancellablePromise<models$0.Module | null> {
    return $Call.ByID(562245282, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetModuleBaseURLs 获取模块的所有前置 URL
 */
export function GetModuleBaseURLs(moduleID: string): $CancellablePromise<models$0.ModuleBaseURL[]> {
    return $Call.ByID(436453937, moduleID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListModules 获取项目下所有模块
 */
export function ListModules(projectID: string): $CancellablePromise<models$0.Module[]> {
    return $Call.ByID(3048297251, projectID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetModuleBaseURL 设置模块在指定环境下的前置 URL
 */
export function SetModuleBaseURL(moduleID: string, environmentID: string, baseURL: string): $CancellablePromise<void> {
    return $Call.ByID(626784604, moduleID, environmentID, baseURL);
}

/**
 * UpdateModule 更新模块信息
 */
export function UpdateModule(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1234066623, id, name);
}

/**
 * UpdateModuleSortOrder 更新模块排序
 */
export function UpdateModuleSortOrder(id: string, sortOrder: number): $CancellablePromise<void> {
    return $Call.ByID(596747721, id, sortOrder);
}

// Private type creation functions
const $$createType0 = models$0.Module.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ModuleBaseURL.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
