// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService 项目管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProject 创建新项目
 */
export function CreateProject(name: string, description: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(917571478, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProject 删除项目及其所有关联数据
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1487253323, id);
}

/**
 * GetProject 根据 ID 获取项目详情
 */
export function GetProject(id: string): $CancellablePromise<models$0.Project | null> {
    return $Call.ByID(803802708, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProjectTree 获取项目的完整树形结构（模块 + 文件夹 + 端点）
 */
export function GetProjectTree(id: string): $CancellablePromise<$models.ModuleTree[]> {
    return $Call.ByID(3820084324, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListProjects 获取所有项目列表
 */
export function ListProjects(): $CancellablePromise<models$0.Project[]> {
    return $Call.ByID(480610827).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ReorderProjects 更新项目排序顺序
 * 接收一个项目 ID 列表，按列表顺序设置每个项目的 sort_order
 */
export function ReorderProjects(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(1431053370, ids);
}

/**
 * UpdateProject 更新项目信息
 */
export function UpdateProject(id: string, name: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(3251974249, id, name, description);
}

// Private type creation functions
const $$createType0 = models$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ModuleTree.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
