// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RequestHistoryService 请求历史服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearModuleHistory 清除模块的所有请求历史
 */
export function ClearModuleHistory(moduleID: string): $CancellablePromise<void> {
    return $Call.ByID(438879706, moduleID);
}

/**
 * DeleteHistory 删除单条请求历史
 */
export function DeleteHistory(id: string): $CancellablePromise<void> {
    return $Call.ByID(2472248758, id);
}

/**
 * GetHistory 获取单条请求历史
 */
export function GetHistory(id: string): $CancellablePromise<models$0.RequestHistory | null> {
    return $Call.ByID(2924227845, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetHistoryDetail 获取请求历史详情（包含解析后的计时信息）
 */
export function GetHistoryDetail(id: string): $CancellablePromise<$models.HistoryDetail | null> {
    return $Call.ByID(2522345972, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListHistoryByModule 获取模块的请求历史（按时间倒序）
 */
export function ListHistoryByModule(moduleID: string, limit: number, offset: number): $CancellablePromise<models$0.RequestHistory[]> {
    return $Call.ByID(485494822, moduleID, limit, offset).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListHistoryByProject 获取项目的请求历史（按时间倒序）
 */
export function ListHistoryByProject(projectID: string, limit: number, offset: number): $CancellablePromise<models$0.RequestHistory[]> {
    return $Call.ByID(1923264971, projectID, limit, offset).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PruneOldHistory 清理超过指定天数的请求历史
 */
export function PruneOldHistory(moduleID: string, days: number): $CancellablePromise<void> {
    return $Call.ByID(1222000092, moduleID, days);
}

// Private type creation functions
const $$createType0 = models$0.RequestHistory.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.HistoryDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
