// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetAllSettings 获取所有设置
 */
export function GetAllSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1156996281).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLanguage 获取语言设置
 */
export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(101063755);
}

/**
 * GetSetting 获取设置值
 */
export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByID(613731099, key);
}

/**
 * GetThemeAccent 获取主题色
 */
export function GetThemeAccent(): $CancellablePromise<string> {
    return $Call.ByID(3250110196);
}

/**
 * GetThemeMode 获取主题模式
 */
export function GetThemeMode(): $CancellablePromise<string> {
    return $Call.ByID(527345705);
}

/**
 * GetUIScale 获取界面缩放比例
 */
export function GetUIScale(): $CancellablePromise<string> {
    return $Call.ByID(144823875);
}

/**
 * SetLanguage 设置语言
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(300304735, lang);
}

/**
 * SetSetting 设置值（upsert）
 */
export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4029266159, key, value);
}

/**
 * SetThemeAccent 设置主题色
 */
export function SetThemeAccent(accent: string): $CancellablePromise<void> {
    return $Call.ByID(2179891832, accent);
}

/**
 * SetThemeMode 设置主题模式
 */
export function SetThemeMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(647960853, mode);
}

/**
 * SetUIScale 设置界面缩放比例
 */
export function SetUIScale(scale: string): $CancellablePromise<void> {
    return $Call.ByID(3814935783, scale);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
