// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ActualRequestInfo 实际发送的请求信息
 */
export class ActualRequestInfo {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string };
    "body": string;

    /** Creates a new ActualRequestInfo instance. */
    constructor($$source: Partial<ActualRequestInfo> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActualRequestInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ActualRequestInfo {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new ActualRequestInfo($$parsedSource as Partial<ActualRequestInfo>);
    }
}

/**
 * CookieInfo Cookie 信息
 */
export class CookieInfo {
    "name": string;
    "value": string;
    "domain": string;
    "path": string;
    "expires": string;
    "httpOnly": boolean;
    "secure": boolean;
    "sameSite": string;

    /** Creates a new CookieInfo instance. */
    constructor($$source: Partial<CookieInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("expires" in $$source)) {
            this["expires"] = "";
        }
        if (!("httpOnly" in $$source)) {
            this["httpOnly"] = false;
        }
        if (!("secure" in $$source)) {
            this["secure"] = false;
        }
        if (!("sameSite" in $$source)) {
            this["sameSite"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CookieInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CookieInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CookieInfo($$parsedSource as Partial<CookieInfo>);
    }
}

/**
 * Endpoint 端点，属于模块或文件夹
 */
export class Endpoint {
    "id": string;
    "moduleId": string;
    "folderId": string | null;
    "name": string;
    "method": string;
    "path": string;
    "bodyType": string;
    "bodyContent": string;
    "contentType": string;
    "timeout": number;
    "followRedirects": boolean;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 关联
     */
    "params"?: EndpointParam[];
    "bodyFields"?: EndpointBodyField[];
    "headers"?: EndpointHeader[];
    "auth"?: EndpointAuth | null;
    "response"?: Response | null;

    /** Creates a new Endpoint instance. */
    constructor($$source: Partial<Endpoint> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("folderId" in $$source)) {
            this["folderId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("bodyType" in $$source)) {
            this["bodyType"] = "";
        }
        if (!("bodyContent" in $$source)) {
            this["bodyContent"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("followRedirects" in $$source)) {
            this["followRedirects"] = false;
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Endpoint instance from a string or object.
     */
    static createFrom($$source: any = {}): Endpoint {
        const $$createField14_0 = $$createType2;
        const $$createField15_0 = $$createType4;
        const $$createField16_0 = $$createType6;
        const $$createField17_0 = $$createType8;
        const $$createField18_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField14_0($$parsedSource["params"]);
        }
        if ("bodyFields" in $$parsedSource) {
            $$parsedSource["bodyFields"] = $$createField15_0($$parsedSource["bodyFields"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField16_0($$parsedSource["headers"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField17_0($$parsedSource["auth"]);
        }
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField18_0($$parsedSource["response"]);
        }
        return new Endpoint($$parsedSource as Partial<Endpoint>);
    }
}

/**
 * EndpointAuth 端点认证信息
 */
export class EndpointAuth {
    "id": string;
    "endpointId": string;

    /**
     * none, basic, bearer
     */
    "type": string;

    /**
     * JSON 格式存储认证数据
     */
    "data": string;

    /** Creates a new EndpointAuth instance. */
    constructor($$source: Partial<EndpointAuth> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointAuth instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointAuth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointAuth($$parsedSource as Partial<EndpointAuth>);
    }
}

/**
 * EndpointBodyField 端点请求体字段（form-data 和 urlencoded）
 */
export class EndpointBodyField {
    "id": string;
    "endpointId": string;
    "name": string;
    "value": string;

    /**
     * text, file
     */
    "fieldType": string;
    "enabled": boolean;

    /** Creates a new EndpointBodyField instance. */
    constructor($$source: Partial<EndpointBodyField> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("fieldType" in $$source)) {
            this["fieldType"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointBodyField instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointBodyField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointBodyField($$parsedSource as Partial<EndpointBodyField>);
    }
}

/**
 * EndpointHeader 端点请求头
 */
export class EndpointHeader {
    "id": string;
    "endpointId": string;
    "name": string;
    "value": string;
    "description": string;
    "enabled": boolean;

    /** Creates a new EndpointHeader instance. */
    constructor($$source: Partial<EndpointHeader> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointHeader instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointHeader {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointHeader($$parsedSource as Partial<EndpointHeader>);
    }
}

/**
 * EndpointParam 端点查询参数
 */
export class EndpointParam {
    "id": string;
    "endpointId": string;

    /**
     * query
     */
    "type": string;
    "name": string;
    "value": string;
    "description": string;
    "enabled": boolean;

    /** Creates a new EndpointParam instance. */
    constructor($$source: Partial<EndpointParam> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointParam instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointParam {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointParam($$parsedSource as Partial<EndpointParam>);
    }
}

/**
 * Environment 环境配置，属于项目
 */
export class Environment {
    "id": string;
    "projectId": string;
    "name": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 关联
     */
    "variables"?: EnvironmentVariable[];

    /** Creates a new Environment instance. */
    constructor($$source: Partial<Environment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     */
    static createFrom($$source: any = {}): Environment {
        const $$createField5_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField5_0($$parsedSource["variables"]);
        }
        return new Environment($$parsedSource as Partial<Environment>);
    }
}

/**
 * EnvironmentVariable 环境变量，属于环境
 */
export class EnvironmentVariable {
    "id": string;
    "environmentId": string;
    "key": string;
    "value": string;
    "description": string;

    /** Creates a new EnvironmentVariable instance. */
    constructor($$source: Partial<EnvironmentVariable> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("environmentId" in $$source)) {
            this["environmentId"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentVariable instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvironmentVariable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentVariable($$parsedSource as Partial<EnvironmentVariable>);
    }
}

/**
 * Folder 文件夹，支持递归嵌套
 */
export class Folder {
    "id": string;
    "moduleId": string;
    "parentId": string | null;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 关联（不存储，仅用于查询）
     */
    "children"?: Folder[];
    "endpoints"?: Endpoint[];

    /** Creates a new Folder instance. */
    constructor($$source: Partial<Folder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("parentId" in $$source)) {
            this["parentId"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     */
    static createFrom($$source: any = {}): Folder {
        const $$createField7_0 = $$createType14;
        const $$createField8_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField7_0($$parsedSource["children"]);
        }
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField8_0($$parsedSource["endpoints"]);
        }
        return new Folder($$parsedSource as Partial<Folder>);
    }
}

/**
 * Module 模块，属于项目
 */
export class Module {
    "id": string;
    "projectId": string;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 关联
     */
    "baseUrls"?: ModuleBaseURL[];

    /** Creates a new Module instance. */
    constructor($$source: Partial<Module> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Module instance from a string or object.
     */
    static createFrom($$source: any = {}): Module {
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseUrls" in $$parsedSource) {
            $$parsedSource["baseUrls"] = $$createField6_0($$parsedSource["baseUrls"]);
        }
        return new Module($$parsedSource as Partial<Module>);
    }
}

/**
 * ModuleBaseURL 模块在各环境下的前置 URL
 */
export class ModuleBaseURL {
    "id": string;
    "moduleId": string;
    "environmentId": string;
    "baseUrl": string;

    /** Creates a new ModuleBaseURL instance. */
    constructor($$source: Partial<ModuleBaseURL> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("environmentId" in $$source)) {
            this["environmentId"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuleBaseURL instance from a string or object.
     */
    static createFrom($$source: any = {}): ModuleBaseURL {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModuleBaseURL($$parsedSource as Partial<ModuleBaseURL>);
    }
}

/**
 * Project 项目模型，顶层容器
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * RequestHistory 请求历史记录，按模块组织
 */
export class RequestHistory {
    "id": string;
    "moduleId": string;
    "endpointId": string | null;
    "method": string;
    "url": string;
    "statusCode": number;

    /**
     * JSON 格式 TimingInfo
     */
    "timing": string;
    "size": number;
    "createdAt": time$0.Time;

    /** Creates a new RequestHistory instance. */
    constructor($$source: Partial<RequestHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("moduleId" in $$source)) {
            this["moduleId"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = null;
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("timing" in $$source)) {
            this["timing"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): RequestHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestHistory($$parsedSource as Partial<RequestHistory>);
    }
}

/**
 * Response 端点最后一次响应，每个端点仅保留一条
 */
export class Response {
    "id": string;
    "endpointId": string;
    "statusCode": number;

    /**
     * JSON 格式
     */
    "headers": string;

    /**
     * 原始响应体
     */
    "body": string;

    /**
     * 响应 Content-Type
     */
    "contentType": string;

    /**
     * JSON 格式
     */
    "cookies": string;

    /**
     * JSON 格式
     */
    "timing": string;

    /**
     * 响应体大小（字节）
     */
    "size": number;

    /**
     * JSON 格式，实际发送的请求信息
     */
    "actualRequest": string;
    "createdAt": time$0.Time;

    /** Creates a new Response instance. */
    constructor($$source: Partial<Response> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("endpointId" in $$source)) {
            this["endpointId"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("headers" in $$source)) {
            this["headers"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("cookies" in $$source)) {
            this["cookies"] = "";
        }
        if (!("timing" in $$source)) {
            this["timing"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("actualRequest" in $$source)) {
            this["actualRequest"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     */
    static createFrom($$source: any = {}): Response {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response($$parsedSource as Partial<Response>);
    }
}

/**
 * TimingInfo 请求计时信息
 */
export class TimingInfo {
    /**
     * DNS 查询耗时（毫秒）
     */
    "dnsLookup": number;

    /**
     * TLS 握手耗时（毫秒）
     */
    "tlsHandshake": number;

    /**
     * TCP 连接耗时（毫秒）
     */
    "tcpConnect": number;

    /**
     * 首字节时间（毫秒）
     */
    "ttfb": number;

    /**
     * 总耗时（毫秒）
     */
    "total": number;

    /** Creates a new TimingInfo instance. */
    constructor($$source: Partial<TimingInfo> = {}) {
        if (!("dnsLookup" in $$source)) {
            this["dnsLookup"] = 0;
        }
        if (!("tlsHandshake" in $$source)) {
            this["tlsHandshake"] = 0;
        }
        if (!("tcpConnect" in $$source)) {
            this["tcpConnect"] = 0;
        }
        if (!("ttfb" in $$source)) {
            this["ttfb"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimingInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TimingInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimingInfo($$parsedSource as Partial<TimingInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = EndpointParam.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = EndpointBodyField.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = EndpointHeader.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = EndpointAuth.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = Response.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = EnvironmentVariable.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Folder.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = Endpoint.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = ModuleBaseURL.createFrom;
const $$createType18 = $Create.Array($$createType17);
